#!/usr/bin/env node
/**
 * GymFlow Server — start.js
 * Auto-generated by build-server.js.
 * Run from inside server/:   node start.js
 *
 * Env vars (see .env.example):
 *   DATABASE_URL  — connection string  (default: SQLite ./data/gymflow.db)
 *   API_PORT      — NestJS port         (default: 4000)
 *   NEXT_PORT     — Next.js port        (default: 3000)
 */
'use strict';

var fs      = require('fs');
var path    = require('path');
var child   = require('child_process');
var spawn    = child.spawn;
var execSync = child.execSync;

// ── Load .env ────────────────────────────────────────────────────────────
var envFile = path.join(__dirname, '.env');
if (fs.existsSync(envFile)) {
  require(path.join(__dirname, 'node_modules', 'dotenv')).config({ path: envFile });
  console.log('[GymFlow] Loaded .env');
} else {
  console.warn('[GymFlow] .env not found — using defaults (SQLite, ports 4000/3000).');
  console.warn('[GymFlow] Tip: cp .env.example .env');
}

// ── Default to SQLite when DATABASE_URL is not set ───────────────────────
if (!process.env.DATABASE_URL) {
  var dataDir = path.join(__dirname, 'data');
  fs.mkdirSync(dataDir, { recursive: true });
  var dbFile = path.join(dataDir, 'gymflow.db').replace(/\\/g, '/');
  process.env.DATABASE_URL = 'file:' + dbFile;
  console.log('[GymFlow] DATABASE_URL defaulting to SQLite: ' + process.env.DATABASE_URL);
}
if ((process.env.DATABASE_URL || '').startsWith('file:')) {
  fs.mkdirSync(path.join(__dirname, 'data'), { recursive: true });
}

var API_PORT  = Number(process.env.API_PORT)  || 4000;
var NEXT_PORT = Number(process.env.NEXT_PORT) || 3000;

// ── Prisma db push (idempotent schema sync) ───────────────────────────────
function setupDatabase() {
  var schema    = path.join(__dirname, 'prisma', 'schema.prisma');
  var binSuffix = process.platform === 'win32' ? 'prisma.cmd' : 'prisma';
  var prismaCli = path.join(__dirname, 'node_modules', '.bin', binSuffix);
  var fallback  = path.join(__dirname, 'node_modules', 'prisma', 'build', 'index.js');
  var cliExpr = fs.existsSync(prismaCli)
    ? '"' + prismaCli + '"'
    : '"' + process.execPath + '" "' + fallback + '"';
  var cmd = cliExpr + ' db push --schema="' + schema + '" --accept-data-loss --skip-generate';
  console.log('[GymFlow] Syncing database schema (prisma db push)...');
  try {
    execSync(cmd, { stdio: 'inherit', env: process.env, cwd: __dirname });
    console.log('[GymFlow] Database ready.\n');
  } catch (err) {
    console.error('\n[GymFlow]  Database setup failed!');
    console.error('[GymFlow]  DATABASE_URL = ' + process.env.DATABASE_URL);
    console.error('[GymFlow]  Check .env and confirm the DB server is reachable.');
    process.exit(1);
  }
}

// ── Start NestJS API ─────────────────────────────────────────────────────
function startApi() {
  var entry = path.join(__dirname, 'api', 'dist', 'main.js');
  if (!fs.existsSync(entry)) {
    console.error('[GymFlow]  api/dist/main.js not found. Run build-server.js first.');
    process.exit(1);
  }
  console.log('[GymFlow] Starting API on port ' + API_PORT + ' ...');
  var proc = spawn(process.execPath, [entry], {
    env:   Object.assign({}, process.env, { API_PORT: String(API_PORT) }),
    cwd:   path.join(__dirname, 'api'),
    stdio: 'inherit',
  });
  proc.on('exit', function (code) {
    console.error('[GymFlow]  API process exited (code ' + code + ')');
    process.exit(code != null ? code : 1);
  });
  return proc;
}

// ── Start Next.js frontend ────────────────────────────────────────────────
function startWeb() {
  var webDir  = path.join(__dirname, 'web');
  var nextBin = path.join(__dirname, 'node_modules', 'next', 'dist', 'bin', 'next');
  if (!fs.existsSync(nextBin)) {
    console.warn('[GymFlow]  next binary not found — frontend will not start.');
    return null;
  }
  console.log('[GymFlow] Starting frontend on port ' + NEXT_PORT + ' ...');
  var proc = spawn(
    process.execPath,
    [nextBin, 'start', '-p', String(NEXT_PORT)],
    {
      env:   Object.assign({}, process.env, { PORT: String(NEXT_PORT), NODE_ENV: 'production' }),
      cwd:   webDir,
      stdio: 'inherit',
    }
  );
  proc.on('exit', function (code) {
    console.warn('[GymFlow]  Frontend process exited (code ' + code + ')');
  });
  return proc;
}

// ── SQLite enum shim — patches @prisma/client when enums are not generated ──
var PRISMA_ENUMS = {
  UserRole:           ['SUPER_ADMIN','GYM_OWNER','BRANCH_MANAGER','RECEPTIONIST','TRAINER','MEMBER'],
  Gender:             ['MALE','FEMALE','OTHER','PREFER_NOT_TO_SAY'],
  MembershipStatus:   ['ACTIVE','INACTIVE','FROZEN','CANCELLED','EXPIRED','PENDING'],
  MembershipType:     ['MONTHLY','ANNUAL','PAY_PER_VISIT','FAMILY','STUDENT','CORPORATE','DAY_PASS'],
  PaymentStatus:      ['PENDING','PAID','FAILED','REFUNDED','PARTIALLY_REFUNDED'],
  PaymentMethod:      ['STRIPE','PAYPAL','APPLE_PAY','GOOGLE_PAY','BANK_TRANSFER','CASH'],
  AttendanceMethod:   ['QR_CODE','RFID','FACE_RECOGNITION','MOBILE_APP','RECEPTION','MANUAL'],
  ClassStatus:        ['SCHEDULED','ONGOING','COMPLETED','CANCELLED'],
  BookingStatus:      ['CONFIRMED','WAITLISTED','CANCELLED','NO_SHOW','ATTENDED'],
  NotificationChannel:['EMAIL','SMS','PUSH','IN_APP','WHATSAPP'],
  NotificationStatus: ['PENDING','SENT','FAILED','READ'],
  StaffShiftStatus:   ['SCHEDULED','CHECKED_IN','CHECKED_OUT','ABSENT'],
  GymPlanTier:        ['STARTER','PROFESSIONAL','ENTERPRISE'],
  GymStatus:          ['ACTIVE','SUSPENDED','TRIAL','CANCELLED'],
  TicketStatus:       ['OPEN','IN_PROGRESS','RESOLVED','CLOSED'],
  TransactionType:    ['SUBSCRIPTION','CLASS_BOOKING','PT_SESSION','PRODUCT_SALE','REFUND','PENALTY'],
};

function patchPrismaEnums() {
  var MARKER = '// === SQLite Enum Shims';
  var jsLines = ['\n' + MARKER + ' ==='];
  Object.keys(PRISMA_ENUMS).forEach(function (name) {
    var pairs = PRISMA_ENUMS[name].map(function (v) { return "  '" + v + "': '" + v + "'"; }).join(',\n');
    jsLines.push('module.exports.' + name + ' = {\n' + pairs + '\n};');
  });
  var jsShim = jsLines.join('\n') + '\n';
  var candidates = [
    path.join(__dirname, 'node_modules', '@prisma',  'client',  'index.js'),
    path.join(__dirname, 'node_modules', '.prisma',  'client',  'default.js'),
  ];
  candidates.forEach(function (f) {
    if (!fs.existsSync(f)) return;
    var src = fs.readFileSync(f, 'utf8');
    if (src.indexOf(MARKER) !== -1) return;
    fs.appendFileSync(f, jsShim, 'utf8');
    console.log('[GymFlow] Enum shims injected \u2192 ' + path.relative(__dirname, f));
  });
}

// ── Boot sequence ─────────────────────────────────────────────────────────
// Patch enum exports when running with SQLite (prisma generate strips enums)
if ((process.env.DATABASE_URL || 'file:').startsWith('file:')) {
  patchPrismaEnums();
}
setupDatabase();

// ── Optional seed (node start.js --seed) ──────────────────────────────────
var ARGS = process.argv.slice(2);
if (ARGS.indexOf('--seed') !== -1) {
  var seedFile = path.join(__dirname, 'seed.js');
  if (fs.existsSync(seedFile)) {
    console.log('[GymFlow] Running seed (--seed flag detected)...');
    try {
      execSync('"' + process.execPath + '" "' + seedFile + '"', {
        stdio: 'inherit',
        env:   process.env,
        cwd:   __dirname,
      });
    } catch (e) {
      console.error('[GymFlow] Seed failed \u2014 continuing server startup anyway.');
    }
  } else {
    console.warn('[GymFlow] --seed: seed.js not found in server/');
  }
}

var apiProc = startApi();
var webProc = startWeb();

// Print banner after processes have had time to initialise
setTimeout(function () {
  var a = String(API_PORT);
  var n = String(NEXT_PORT);
  console.log('\n\u2554' + '\u2550'.repeat(46) + '\u2557');
  console.log('\u2551  GymFlow is running!                           \u2551');
  console.log('\u2560' + '\u2550'.repeat(46) + '\u2563');
  console.log('\u2551  API      \u2192  http://localhost:' + a + '/api/v1    \u2551');
  console.log('\u2551  Docs     \u2192  http://localhost:' + a + '/api/docs  \u2551');
  console.log('\u2551  Frontend \u2192  http://localhost:' + n + '           \u2551');
  console.log('\u255a' + '\u2550'.repeat(46) + '\u255d\n');
}, 6000);

// ── Graceful shutdown ─────────────────────────────────────────────────────
function shutdown(sig) {
  console.log('\n[GymFlow] Received ' + sig + ' — shutting down...');
  if (apiProc) apiProc.kill('SIGTERM');
  if (webProc) webProc.kill('SIGTERM');
  setTimeout(function () { process.exit(0); }, 4000).unref();
}
['SIGTERM', 'SIGINT'].forEach(function (sig) { process.on(sig, function () { shutdown(sig); }); });